cdcservice:
  build: ./eventuate-tram-cdc-mysql-service
  ports:
    - "8099:8080"
  links:
    - mssql
    - kafka
    - zookeeper
  environment:
    SPRING_DATASOURCE_URL: jdbc:sqlserver://172.17.0.1:1433;databaseName=eventuate
    SPRING_DATASOURCE_USERNAME: sa
    SPRING_DATASOURCE_PASSWORD: Eventuate123!
    SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.microsoft.sqlserver.jdbc.SQLServerDriver
    EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
    EVENTUATELOCAL_CDC_POLLING_INTERVAL_IN_MILLISECONDS: 500
    EVENTUATELOCAL_CDC_MAX_EVENTS_PER_POLLING: 1000
    EVENTUATELOCAL_CDC_MAX_ATTEMPTS_FOR_POLLING: 100
    EVENTUATELOCAL_CDC_POLLING_RETRY_INTERVAL_IN_MILLISECONDS: 500
    EVENTUATELOCAL_CDC_READER_NAME: ${EVENTUATELOCAL_CDC_READER_NAME}
    SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
